{
	"version": 1687162757,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/bucketa-sheet0.png",
		"images/oil-sheet0.png",
		"images/oilspawner-sheet0.png",
		"images/assetbackground-sheet0.png",
		"images/oilspawnmanager-sheet0.png",
		"images/oilspawner2-sheet0.png",
		"images/oilspawner3-sheet0.png",
		"images/oilspawner4-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/01bangunanpom-sheet0.png",
		"images/02tokokopi-sheet0.png",
		"images/03indomaret-sheet0.png",
		"images/04pom-sheet0.png",
		"images/05motor-sheet0.png",
		"images/06mobil-sheet0.png",
		"images/lantai-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/bawahan-sheet0.png",
		"images/bawahan-sheet1.png",
		"images/bawahan-sheet2.png",
		"images/turn-sheet0.png",
		"images/ui-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/ui2-sheet0.png",
		"images/resume-sheet0.png",
		"images/help-sheet0.png",
		"images/settingsui-sheet0.png",
		"images/quitbutton-sheet0.png",
		"images/mistakesicon-sheet0.png",
		"images/mistakesicon-sheet1.png",
		"images/playbutton-sheet0.png",
		"images/musictooglee-sheet0.png",
		"images/playagainbutton-sheet0.png",
		"images/mainmenubutton2-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/oiloutleft-sheet0.png",
		"images/oiloutleft-sheet1.png",
		"images/oiloutright-sheet0.png",
		"images/rokok-sheet0.png",
		"images/kompor1-sheet0.png",
		"images/ojol-sheet0.png",
		"images/sassygirl-sheet0.png",
		"images/sassygirl-sheet1.png",
		"images/sassygirl-sheet2.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/settingbutton-sheet0.png",
		"images/sprite15-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/soundtoogle-sheet0.png",
		"images/close-sheet0.png",
		"images/questionmark-sheet0.png",
		"images/instruction-sheet0.png",
		"images/instruction-sheet1.png",
		"images/instructionnextpage-sheet0.png",
		"images/credit-sheet0.png",
		"images/creditpanel-sheet0.png",
		"images/logo1-sheet0.png",
		"images/logo2-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/01bangunanpom2-sheet0.png",
		"images/01bangunanpom3-sheet0.png",
		"images/disable-sheet0.png",
		"media/game over sfx.m4a",
		"media/game over sfx.ogg",
		"media/get point sfx.m4a",
		"media/get point sfx.ogg",
		"media/menu button clicked sfx.m4a",
		"media/menu button clicked sfx.ogg",
		"media/move button clicked sfx.m4a",
		"media/move button clicked sfx.ogg",
		"media/oil fail to catch sfx.m4a",
		"media/oil fail to catch sfx.ogg",
		"media/pause button clicked sfx.m4a",
		"media/pause button clicked sfx.ogg",
		"media/switch postition sfx.m4a",
		"media/switch postition sfx.ogg",
		"media/water drop sfx.m4a",
		"media/water drop sfx.ogg",
		"media/water falling sfx.m4a",
		"media/water falling sfx.ogg",
		"media/water get sfx.m4a",
		"media/water get sfx.ogg",
		"media/game start sfx.m4a",
		"media/game start sfx.ogg",
		"media/oilpanic.m4a",
		"media/2.m4a",
		"media/2.ogg",
		"media/title bgm.m4a",
		"media/title bgm.ogg",
		"media/town background ambient noise.m4a",
		"media/town background ambient noise.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}